services:
  redis:
    image: redis
    ports:
     - "${redis_port}:${redis_port}"
  app:
    build: .
    environment:
      - grpc_port=${grpc_port}
      - redis_ip=${redis_ip}
      - redis_pass=${redis_pass}
      - redis_port=${redis_port}
      - rest_port=${rest_port}
    ports:
      - "${rest_port}"
      - "${grpc_port}"